baseURL = 'https://demo.redopsbay.dev'
languageCode = 'en-us'
title = 'DevOps Demo'
theme = 'hugo-theme-learn'

[params]
  #editURL = ""
  # Author of the site, will be used in meta information
  author = "Alfred Valderrama"
  # Description of the site, will be used in meta information
  description = "Basic DevOps automation demonstration"
  titleSeparator = "-"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30
